# Use the official MySQL 8.0 image from Docker Hub
FROM mysql:8.0

# Set the MySQL root password (change it to your desired password)
ENV MYSQL_ROOT_PASSWORD=rishikumar
ENV MYSQL_HOST=0.0.0.0
# Create a database named loginapp1
ENV MYSQL_DATABASE=loginapp1

# Expose port 3306 to allow external connections
EXPOSE 3306

